### PR TITLE
fixups for firmware updating

### PR DESCRIPTION
**Pull request by douglasbakkum**
- need to read sig as binary data
- update gui messages
- disable firmware menu when device not connected

### CODE REVIEW

**Comment by douglasbakkum** [comment]
Added two more commits.
- Renamed the menu item from `Firmware` to `Options` because I thought this would be more flexible in the future - i.e. might add or move more items to an Options menu, while a Firmware menu would only ever have one item.
- As discussed, block the app from running if the firmware is not compatible in order to prevent confusion and heart attacks when someone's coins do not appear or cannot be spent.

**Comment by douglasbakkum** [comment]
The blocked app looks like:
screen shot 2016-06-30 at 13 33 12

I made a firmware download page: https://digitalbitbox.com/firmware

Note that this commit will prevent your dbb from running. Blocking is done by checking if the version string begins with `v1.` or `v0.`. The download at the bottom of the webpage can be uploaded to a dev dbb - the firmware version string is `v2.0.0-rc.1`.

**Comment by jonasschnelli** [comment]
Added to https://github.com/digitalbitbox/dbb-app/pull/196/commits.

**Comment by jonasschnelli** [comment]
Closing.

**Pull request closed without merging**
